apiVersion: core.krateo.io/v1alpha1
kind: CompositionDefinition
metadata:
  name: keycloak-config-kog
  namespace: krateo-system
spec:
  chart:
    url: oci://ghcr.io/krateo-blueprints/charts/keycloak-config-kog
    version: CHART_VERSION
